# Generated by Django 3.0.7 on 2020-06-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0002_auto_20200628_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OFFICE_PIS.Post'),
        ),
    ]
