# Generated by Django 3.0.7 on 2020-06-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0003_auto_20200628_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OFFICE_PIS.Office'),
        ),
    ]
