# Generated by Django 3.0.7 on 2020-06-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0004_staff_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
        ),
    ]
