# Generated by Django 3.0.7 on 2020-07-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0006_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OFFICE_PIS.Question'),
        ),
    ]
