# Generated by Django 3.0.7 on 2020-07-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0008_auto_20200702_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
        ),
        migrations.AlterField(
            model_name='desiredperson',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
        ),
        migrations.AlterField(
            model_name='family',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
