# Generated by Django 3.0.7 on 2020-07-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0009_auto_20200703_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DarbandiInfo',
            new_name='Darbandi',
        ),
    ]
