# Generated by Django 3.0.7 on 2020-07-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0011_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
            preserve_default=False,
        ),
    ]
