# Generated by Django 3.0.7 on 2020-07-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0012_treatment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='office',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Office'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Post'),
        ),
    ]
