# Generated by Django 3.0.7 on 2020-07-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0014_auto_20200719_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff'),
            preserve_default=False,
        ),
    ]
