# Generated by Django 3.0.7 on 2020-07-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0015_auto_20200719_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Office'),
            preserve_default=False,
        ),
    ]
