# Generated by Django 3.0.7 on 2020-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0016_service_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darbandi',
            old_name='post_number',
            new_name='current_post',
        ),
        migrations.AddField(
            model_name='darbandi',
            name='total_post',
            field=models.IntegerField(default=1),
        ),
    ]
