# Generated by Django 3.0.7 on 2020-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0018_auto_20200726_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pis/'),
        ),
    ]
