# Generated by Django 3.0.7 on 2020-07-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OFFICE_PIS', '0019_auto_20200726_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, upload_to='documents/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OFFICE_PIS.Staff')),
            ],
        ),
    ]
